"""add fund_type to categories

Revision ID: a663b2a72167
Revises: 67c7854652fa
Create Date: 2026-06-10 10:33:03.095871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a663b2a72167'
down_revision: Union[str, Sequence[str], None] = '67c7854652fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('fund_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'fund_type')
    # ### end Alembic commands ###
